pod 'AFNetworking', :path => '/Users/simon/Documents/code/ObjC/GitHub/AFNetworking/'
pod 'KZPropertyMapper', :path => '/Users/simon/Documents/code/ObjC/GitHub/KZPropertyMapper/'
pod 'FCYAsserts', '~> 1.2'
pod 'SDURLCache'
